jobs:
  
  - job: linux
    displayName: Linux
    pool:
      vmImage: "ubuntu-16.04"

    strategy:
      matrix:
        node_10_x:
          node_version: "10.x"

    steps:
      - template: linux.yml
    
  - job: win
    displayName: Windows
    pool:
      vmImage: "windows-2019"

    strategy:
      matrix:
        node_10_x:
          node_version: "10.x"

    steps:
      - template: win.yml

  - job: mac
    displayName: MacOS
    pool:
      vmImage: "macos-10.13"

    strategy:
      matrix:
        node_10_x:
          node_version: "10.x"

    steps:
      - template: mac.yml

  - job: github_releases
    pool:
      vmImage: "ubuntu-16.04"
    dependsOn:
      - win
      - linux
      - mac
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    steps:
      - template: github_releases.yml
